config/routes.rb
Rails.application.routes.draw do
  
  resources :claro_manager_by_lines

  resources :claro_transaction_by_line_claros

  resources :claro_transaction_by_lines

  resources :header_manager_claros

  resources :pdf_files

  devise_for :users
  
  resources :claro_extracts

  resources :consumers

  resources :companies

  resources :allotments

  resources :type_companies

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :lote_wizard

  resources :process_pdf

  resources :data_pdfs

  namespace :consumer_area do
    resources :reports
  end

  root 'consumers#index'

end

app/models/allotment.rb
class Allotment < ActiveRecord::Base
   
   belongs_to :consumers, class_name: Consumer

   validates :name, :presence => true

   enum status: [:in_progress, :completed, :invoiced, :newer]

   def consumer_name
   		id = self.id
   		#binding.pry
   		return "#{Consumer.find_by_id(self.consumers_id).name}"
   end

end

app/models/claro_extract.rb
class ClaroExtract < ActiveRecord::Base
 

  belongs_to :allotments, class_name: Allotment

  validates :line, :presence => true
  #validates :content, :presence => true
  validates :allotment_id, :presence => true
end

app/models/claro_manager_by_line.rb
class ClaroManagerByLine < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
	

	validates :name, :presence => true
	validates :type_companies_id,  :presence => true
	belongs_to :type_companies, class_name: TypeCompany
	
end

app/models/consumer.rb
class Consumer < ActiveRecord::Base
	
end

app/models/header_manager_claro.rb
class HeaderManagerClaro < ActiveRecord::Base
end

app/models/pdf_file.rb
class PdfFile < ActiveRecord::Base
	
	attachment :pdf_file, extension: "pdf"
	
	validates :pdf_file, presence: true
	validates :allotments_id, presence: true
	validates :company_id, presence: true


	def lote_name
		return "#{Allotment.find_by_id(self.allotments_id).name}"
	end

end

app/models/type_company.rb
class TypeCompany < ActiveRecord::Base

	validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  #before_action :authenticate_user!

 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vivo_extract.rb
class VivoExtract < ActiveRecord::Base
  belongs_to :allotment
  belongs_to :pdf_file
end

app/models/vivo_group_word.rb
class VivoGroupWord < ActiveRecord::Base
end

app/models/vivo_header_manager.rb
class VivoHeaderManager < ActiveRecord::Base
  belongs_to :allotment
  belongs_to :pdf_file

  #enum type_enclosed: [:min, :gb, :regular, :mb]


end

app/controllers/pdf_files_controller.rb
class PdfFilesController < ApplicationController
  before_action :set_pdf_file, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  before_filter :authorize_admin, only: :index

  def authorize_admin
    redirect_to :back, :status => 401 unless current_user.admin
    #redirects to previous page
  end

  # GET /pdf_files
  # GET /pdf_files.json
  def index
    #binding.pry
    @lote = Allotment.find_by_token "#{params["id"]}"
    @pdf_files = PdfFile.where("allotments_id = ?", @lote.id)

  end

  # GET /pdf_files/1
  # GET /pdf_files/1.json
  def show
  end

  # GET /pdf_files/new
  def new
    @pdf_file = PdfFile.new
    @token = params["id"]
  end

  # GET /pdf_files/1/edit
  def edit
  end

  # POST /pdf_files
  # POST /pdf_files.json
  def create
    
    @token = params["pdf_file"]["allotments_id"]

    @pdf_file = PdfFile.new(pdf_file_params)
    
    @pdf_file.allotments_id = Allotment.find_by_token("#{pdf_file_params["allotments_id"]}").id

    respond_to do |format|

      if @pdf_file.save

        #binding.pry
        
        @pdf_file.name = pdf_file_params["pdf_file"].original_filename
        
        @pdf_file.save!

        format.html { redirect_to pdf_files_path(:id=>"#{pdf_file_params["allotments_id"]}"), notice: 'Pdf file was successfully created.' }
        format.json { render :show, status: :created, location: @pdf_file }
      else
        format.html {render :new}
        format.json { render json: @pdf_file.errors, status: :unprocessable_entity }
      end
    end
  end

  def download
    send_file Refile.attachment_url(@pdf_file, :pdf_file), type: @pdf_file.pdf_file_content_type, disposition: :attachment
  end

  # PATCH/PUT /pdf_files/1
  # PATCH/PUT /pdf_files/1.json
  def update
    respond_to do |format|
      if @pdf_file.update(pdf_file_params)
        format.html { redirect_to @pdf_file, notice: 'Pdf file was successfully updated.' }
        format.json { render :show, status: :ok, location: @pdf_file }
      else
        format.html { render :edit }
        format.json { render json: @pdf_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pdf_files/1
  # DELETE /pdf_files/1.json
  def destroy
    @pdf_file.destroy
    respond_to do |format|
      format.html { redirect_to pdf_files_url, notice: 'Pdf file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pdf_file
      @pdf_file = PdfFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pdf_file_params
      params.require(:pdf_file).permit(:name, :path, :type, :allotments_id, :pdf_file, :company_id)
    end
end

app/helpers/allotments_helper.rb
module AllotmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/consumers_helper.rb
module ConsumersHelper
end

app/helpers/data_pdfs_helper.rb
module DataPdfsHelper
end

app/helpers/lote_wizard_helper.rb
module LoteWizardHelper
end

app/helpers/new_lote_helper.rb
module NewLoteHelper
end

app/helpers/pdf_files_helper.rb
module PdfFilesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/process_pdf_helper.rb
module ProcessPdfHelper
end

app/views/pdf_files/_form.html.erb
  <%= form_for(@pdf_file, :multipart => true) do |f| %>
  <% if @pdf_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pdf_file.errors.count, "error") %> prohibited this pdf_file from being saved:</h2>

      <ul>
      <% @pdf_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.attachment_field :pdf_file, direct: true, :class=>"form-control" %>

  <div class="field">
    <%= f.label :Operadora %><br />
    <%= f.select :company_id, options_for_select(Company.all.map{|s|[s.name, s.id]}) %>
  </div>

  <div class="field" style="display:none">
    <%= f.label :allotments_id %><br>
    <%= f.text_field :allotments_id, :value => @token%>
  </div>

  <% if false %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :path %><br>
    <%= f.text_field :path %>
  </div>
  <div class="form-group">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  
  <% end %>
  <br>
  <div class="form-group">
    <%= f.submit class: 'btn btn-default' %>
  </div>

<% end %>
<script type="text/javascript">
  function disable_button(obj){
    $(obj).attr("disabled", "disabled");
  }
</script>

app/views/pdf_files/edit.html.erb
<h1>Editing Pdf File</h1>

<%= render 'form' %>

<%= link_to 'Show', @pdf_file %> |
<%= link_to 'Back', pdf_files_path %>

app/views/pdf_files/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Cadastro de Lotes</h2>
  </div>
  <div class="col-lg-2">

  </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5>Wizard criação de lote</h5>
        </div>
        <div class="ibox-content">
          <div class="wizard-big wizard clearfix" role="application" novalidate="novalidate">
            <div class="steps clearfix">
              <ul role="tablist">
                <li role="tab" class="disabled" aria-disabled="true">
                  <a aria-controls="form-p-0" href="#" id="form-t-0">
                    <span class="current-info audible">current step: </span>
                    <span class="number">1.</span> Criação do lote
                  </a>
                </li>
                <li role="tab" class="first current" aria-disabled="false" aria-selected="true">
                  <a aria-controls="form-p-1" href="#" id="form-t-1">
                    <span class="number">2.</span> Envio de Arquivos PDF
                  </a>
                </li>
                <li role="tab" class="disabled" aria-disabled="true">
                  <a aria-controls="form-p-2" href="#" id="form-t-2">
                    <span class="number">3.</span>Processamento
                  </a>
                </li>
              </ul>
            </div>
            <div class="content clearfix">    
              <h1 id="form-h-0" tabindex="-1" class="title current">Lote</h1>
              <fieldset id="form-p-1" role="tabpanel" aria-labelledby="form-h-0" class="body current" aria-hidden="false">
                <h2>Arquivos do lote: <%= @lote.name %></h2>
                <div class="row">
                  <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                      <div class="ibox-title">
                        <h5>Dados</h5>
                      </div>
                      <div class="ibox-content">
                        <table class="table">
                          <thead>
                          <tr>
                            <th>Name</th>
                            <th>Lote</th>
                            <th colspan="3"></th>
                          </tr>
                          </thead>
                          <tbody>
                          <% @pdf_files.each do |pdf_file| %>
                          <tr>
                            <td><%= link_to pdf_file.name, attachment_url(pdf_file, :pdf_file, filename: pdf_file.name)%></td>
                            <td><%= pdf_file.lote_name %></td>
                            <% if false %>
                            <td><%= link_to 'Show', pdf_file %></td>
                            <td><%= link_to 'Edit', edit_pdf_file_path(pdf_file) %></td>
                            <td><%= link_to 'Destroy', pdf_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                            <% end %>
                          </tr>
                          <% end %>
                        </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
                <%= link_to 'Novo PDF', new_pdf_file_path(id:@lote.token), :class=>"btn btn-w-m btn-default" %>
                <% if  @pdf_files.count > 0 %>
                <%= link_to 'Processar PDF', process_pdf_index_path(id:@lote.token), :class=>"btn btn-w-m btn-warning" %>
                <% end %>
              </div>
            </fieldset>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/pdf_files/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-lg-10">
		<h2>Cadastro de Lotes</h2>
	</div>
	<div class="col-lg-2">

	</div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox">
				<div class="ibox-title">
					<h5>Wizard criação de lote</h5>
				</div>
				<div class="ibox-content">
					<div class="wizard-big wizard clearfix" role="application" novalidate="novalidate">
						<div class="steps clearfix">
							<ul role="tablist">
								<li role="tab" class="disabled" aria-disabled="true">
				                  <a aria-controls="form-p-0" href="#" id="form-t-0">
				                    <span class="current-info audible">current step: </span>
				                    <span class="number">1.</span> Criação do lote
				                  </a>
				                </li>
				                <li role="tab" class="first current" aria-disabled="false" aria-selected="true">
				                  <a aria-controls="form-p-1" href="#form-h-1" id="form-t-1">
				                    <span class="number">2.</span> Envio de Arquivos PDF
				                  </a>
				                </li>
				                <li role="tab" class="disabled" aria-disabled="true">
				                  <a aria-controls="form-p-2" href="#form-h-2" id="form-t-2">
				                    <span class="number">3.</span>Processamento
				                  </a>
				                </li>
							</ul>
						</div>
						<div class="content clearfix">		
							<h1 id="form-h-0" tabindex="-1" class="title current">Lote</h1>
							<fieldset id="form-p-0" role="tabpanel" aria-labelledby="form-h-0" class="body current" aria-hidden="false">
								<h2>Envio de Arquivos PDF</h2>
								<div class="row">
									<div class="col-lg-8">
										<%= render 'form' %>
									</div>
								</div>
							</fieldset>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$( document ).ready(function() {
    	$("#pdf_file_company_id").addClass( "form-control" );

    	$('#pdf_file_company_id').append($('<option>', { 
        	value: "" ,
        	text : "",
        	selected : true 
    	}));

	});
</script>

app/views/pdf_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pdf_file.name %>
</p>

<p>
  <strong>Allotment:</strong>
  <%= @pdf_file.allotments_id %>
</p>

<%= link_to 'Edit', edit_pdf_file_path(@pdf_file) %> |
<%= link_to 'Back', pdf_files_path %>