config/routes.rb
Rails.application.routes.draw do
  
  resources :claro_manager_by_lines

  resources :claro_transaction_by_line_claros

  resources :claro_transaction_by_lines

  resources :header_manager_claros

  resources :pdf_files

  devise_for :users
  
  resources :claro_extracts

  resources :consumers

  resources :companies

  resources :allotments

  resources :type_companies

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :lote_wizard

  resources :process_pdf

  resources :data_pdfs

  namespace :consumer_area do
    resources :reports
  end

  root 'consumers#index'

end

app/models/allotment.rb
class Allotment < ActiveRecord::Base
   
   belongs_to :consumers, class_name: Consumer

   validates :name, :presence => true

   enum status: [:in_progress, :completed, :invoiced, :newer]

   def consumer_name
   		id = self.id
   		#binding.pry
   		return "#{Consumer.find_by_id(self.consumers_id).name}"
   end

end

app/models/claro_extract.rb
class ClaroExtract < ActiveRecord::Base
 

  belongs_to :allotments, class_name: Allotment

  validates :line, :presence => true
  #validates :content, :presence => true
  validates :allotment_id, :presence => true
end

app/models/claro_manager_by_line.rb
class ClaroManagerByLine < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
	

	validates :name, :presence => true
	validates :type_companies_id,  :presence => true
	belongs_to :type_companies, class_name: TypeCompany
	
end

app/models/consumer.rb
class Consumer < ActiveRecord::Base
	
end

app/models/header_manager_claro.rb
class HeaderManagerClaro < ActiveRecord::Base
end

app/models/pdf_file.rb
class PdfFile < ActiveRecord::Base
	
	attachment :pdf_file, extension: "pdf"
	
	validates :pdf_file, presence: true
	validates :allotments_id, presence: true
	validates :company_id, presence: true


	def lote_name
		return "#{Allotment.find_by_id(self.allotments_id).name}"
	end

end

app/models/type_company.rb
class TypeCompany < ActiveRecord::Base

	validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  #before_action :authenticate_user!

 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vivo_extract.rb
class VivoExtract < ActiveRecord::Base
  belongs_to :allotment
  belongs_to :pdf_file
end

app/models/vivo_group_word.rb
class VivoGroupWord < ActiveRecord::Base
end

app/models/vivo_header_manager.rb
class VivoHeaderManager < ActiveRecord::Base
  belongs_to :allotment
  belongs_to :pdf_file

  #enum type_enclosed: [:min, :gb, :regular, :mb]


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  before_filter :authorize_admin, only: :index

  def authorize_admin
    redirect_to :back, :status => 401 unless current_user.admin
    #redirects to previous page
  end

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :type_companies_id)
    end
end

app/helpers/allotments_helper.rb
module AllotmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/consumers_helper.rb
module ConsumersHelper
end

app/helpers/data_pdfs_helper.rb
module DataPdfsHelper
end

app/helpers/lote_wizard_helper.rb
module LoteWizardHelper
end

app/helpers/new_lote_helper.rb
module NewLoteHelper
end

app/helpers/pdf_files_helper.rb
module PdfFilesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/process_pdf_helper.rb
module ProcessPdfHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type_companies_id %><br>
    <%= f.text_field :type_companies_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type companies</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.type_companies %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Type companies:</strong>
  <%= @company.type_companies %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>