config/routes.rb
Rails.application.routes.draw do
  
  resources :claro_manager_by_lines

  resources :claro_transaction_by_line_claros

  resources :claro_transaction_by_lines

  resources :header_manager_claros

  resources :pdf_files

  devise_for :users
  
  resources :claro_extracts

  resources :consumers

  resources :companies

  resources :allotments

  resources :type_companies

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :lote_wizard

  resources :process_pdf

  resources :data_pdfs

  namespace :consumer_area do
    resources :reports
  end

  root 'consumers#index'

end

app/models/allotment.rb
class Allotment < ActiveRecord::Base
   
   belongs_to :consumers, class_name: Consumer

   validates :name, :presence => true

   enum status: [:in_progress, :completed, :invoiced, :newer]

   def consumer_name
   		id = self.id
   		#binding.pry
   		return "#{Consumer.find_by_id(self.consumers_id).name}"
   end

end

app/models/claro_extract.rb
class ClaroExtract < ActiveRecord::Base
 

  belongs_to :allotments, class_name: Allotment

  validates :line, :presence => true
  #validates :content, :presence => true
  validates :allotment_id, :presence => true
end

app/models/claro_manager_by_line.rb
class ClaroManagerByLine < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
	

	validates :name, :presence => true
	validates :type_companies_id,  :presence => true
	belongs_to :type_companies, class_name: TypeCompany
	
end

app/models/consumer.rb
class Consumer < ActiveRecord::Base
	
end

app/models/header_manager_claro.rb
class HeaderManagerClaro < ActiveRecord::Base
end

app/models/pdf_file.rb
class PdfFile < ActiveRecord::Base
	
	attachment :pdf_file, extension: "pdf"
	
	validates :pdf_file, presence: true
	validates :allotments_id, presence: true
	validates :company_id, presence: true


	def lote_name
		return "#{Allotment.find_by_id(self.allotments_id).name}"
	end

end

app/models/type_company.rb
class TypeCompany < ActiveRecord::Base

	validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  #before_action :authenticate_user!

 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vivo_extract.rb
class VivoExtract < ActiveRecord::Base
  belongs_to :allotment
  belongs_to :pdf_file
end

app/models/vivo_group_word.rb
class VivoGroupWord < ActiveRecord::Base
end

app/models/vivo_header_manager.rb
class VivoHeaderManager < ActiveRecord::Base
  belongs_to :allotment
  belongs_to :pdf_file

  #enum type_enclosed: [:min, :gb, :regular, :mb]


end

app/controllers/allotments_controller.rb
class AllotmentsController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_allotment, only: [:show, :edit, :update, :destroy]

  before_filter :authorize_admin, only: :index

  def authorize_admin
    redirect_to :back, :status => 401 unless current_user.admin
    #redirects to previous page
  end

  # GET /allotments
  # GET /allotments.json
  def index
    @allotments = Allotment.all
  end

  # GET /allotments/1
  # GET /allotments/1.json
  def show
  end

  # GET /allotments/new
  def new
    @allotment = Allotment.new
  end

  # GET /allotments/1/edit
  def edit
  end

  # POST /allotments
  # POST /allotments.json

  

  def create
    
    @allotment = Allotment.new(allotment_params)

    @allotment.token = Devise.friendly_token

    respond_to do |format|
      
      if @allotment.save
        
        @allotment.newer! 
        
        format.html { redirect_to pdf_files_path(:id => @allotment.token), notice: 'Allotment was successfully created.' }
        format.json { render :show, status: :created, location: @allotment }
      
      else
        
        format.html { render :new }
        format.json { render json: @allotment.errors, status: :unprocessable_entity }
      
      end
    end
  end


  # PATCH/PUT /allotments/1
  # PATCH/PUT /allotments/1.json
  def update
    respond_to do |format|
      if @allotment.update(allotment_params)
        format.html { redirect_to @allotment, notice: 'Allotment was successfully updated.' }
        format.json { render :show, status: :ok, location: @allotment }
      else
        format.html { render :edit }
        format.json { render json: @allotment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allotments/1
  # DELETE /allotments/1.json
  def destroy
    @allotment.destroy
    respond_to do |format|
      format.html { redirect_to allotments_url, notice: 'Allotment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_allotment
      @allotment = Allotment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def allotment_params
      params.require(:allotment).permit(:name, :consumers_id, :status)
    end
end

app/helpers/allotments_helper.rb
module AllotmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/consumers_helper.rb
module ConsumersHelper
end

app/helpers/data_pdfs_helper.rb
module DataPdfsHelper
end

app/helpers/lote_wizard_helper.rb
module LoteWizardHelper
end

app/helpers/new_lote_helper.rb
module NewLoteHelper
end

app/helpers/pdf_files_helper.rb
module PdfFilesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/process_pdf_helper.rb
module ProcessPdfHelper
end

app/views/allotments/_form.html.erb
<%= form_for(@allotment) do |f| %>
  <% if @allotment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@allotment.errors.count, "error") %> prohibited this allotment from being saved:</h2>

      <ul>
      <% @allotment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :consumers_id %><br>
    <%= f.collection_select :consumers_id, Consumer.all, :id, :name %>
  </div>

  <% if false %>
  <div class="form-group">
    <%= f.label :status %><br>
    <%= f.select :status, Allotment.statuses.keys.to_a%>
  </div>
  <% end %>
  
  <div class="form-group">
    <%= f.submit class: 'btn btn-default'%>
  </div>
<% end %>

app/views/allotments/edit.html.erb
<h1>Editing Allotment</h1>

<%= render 'form' %>

<%= link_to 'Show', @allotment %> |
<%= link_to 'Back', allotments_path %>

app/views/allotments/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Cadastro de Lotes</h2>
  </div>
  <div class="col-lg-2">

  </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-11">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Dados</h5>
        </div>
        <div class="ibox-content">
          <table class="table">
            <thead>
            <tr>
              <th>Name</th>
              <th>Consumers</th>
              <th>Status</th>
              <th>Data de Criação</th>
              <th>Data Atualização</th>
              <% if false %>
              <th colspan="3"></th>
              <% end %>
            </tr>
            </thead>
            <tbody>
              <% @allotments.each do |allotment| %>
                <tr>
                  <td><%= link_to allotment.name, "/pdf_files?id=#{allotment.token}"   %></td>
                  <td><%= allotment.consumer_name %></td>
                  <td><%= allotment.status %></td>
                  <td><%= allotment.created_at %></td>
                  <td><%= allotment.updated_at %></td>
                  <% if false %>
                  <td><%= link_to 'Show', allotment %></td>
                  <td><%= link_to 'Edit', edit_allotment_path(allotment) %></td>
                  <td><%= link_to 'Destroy', allotment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <%= link_to 'New Lote', new_allotment_path, {class: "btn btn-w-m btn-default"} %>
</div>

app/views/allotments/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-lg-10">
		<h2>Cadastro de Lotes</h2>
	</div>
	<div class="col-lg-2">

	</div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox">
				<div class="ibox-title">
					<h5>Wizard criação de lote</h5>
				</div>
				<div class="ibox-content">
					<div class="wizard-big wizard clearfix" role="application" novalidate="novalidate">
						<div class="steps clearfix">
							<ul role="tablist">
								<li role="tab" class="first current" aria-disabled="false" aria-selected="true">
									<a aria-controls="form-p-0" href="#form-h-0" id="form-t-0">
										<span class="current-info audible">current step: </span>
										<span class="number">1.</span> Criação do lote
									</a>
								</li>
								<li role="tab" class="disabled" aria-disabled="true">
									<a aria-controls="form-p-1" href="#" id="form-t-1">
										<span class="number">2.</span> Envio de Arquivos PDF
									</a>
								</li>
								<li role="tab" class="disabled" aria-disabled="true">
									<a aria-controls="form-p-2" href="#" id="form-t-2">
										<span class="number">3.</span>Processamento
									</a>
								</li>
							</ul>
						</div>
						<div class="content clearfix">		
							<h1 id="form-h-0" tabindex="-1" class="title current">Lote</h1>
							<fieldset id="form-p-0" role="tabpanel" aria-labelledby="form-h-0" class="body current" aria-hidden="false">
								<h2>Início criação do Lote</h2>
								<div class="row">
									<div class="col-lg-8">
										<%= render 'form' %>
									</div>
								</div>
							</fieldset>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$( document ).ready(function() {
    	$("#allotment_consumers_id").addClass( "form-control" );
	});
</script>

app/views/allotments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @allotment.name %>
</p>

<p>
  <strong>Consumers:</strong>
  <%= @allotment.consumers %>
</p>

<p>
  <strong>Status:</strong>
  <%= @allotment.status %>
</p>

<%= link_to 'Edit', edit_allotment_path(@allotment) %> |
<%= link_to 'Back', allotments_path %>