config/routes.rb
Rails.application.routes.draw do
  
  resources :claro_manager_by_lines

  resources :claro_transaction_by_line_claros

  resources :claro_transaction_by_lines

  resources :header_manager_claros

  resources :pdf_files

  devise_for :users
  
  resources :claro_extracts

  resources :consumers

  resources :companies

  resources :allotments

  resources :type_companies

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :lote_wizard

  resources :process_pdf

  resources :data_pdfs

  namespace :consumer_area do
    resources :reports
  end

  root 'consumers#index'

end

app/models/allotment.rb
class Allotment < ActiveRecord::Base
   
   belongs_to :consumers, class_name: Consumer

   validates :name, :presence => true

   enum status: [:in_progress, :completed, :invoiced, :newer]

   def consumer_name
   		id = self.id
   		#binding.pry
   		return "#{Consumer.find_by_id(self.consumers_id).name}"
   end

end

app/models/claro_extract.rb
class ClaroExtract < ActiveRecord::Base
 

  belongs_to :allotments, class_name: Allotment

  validates :line, :presence => true
  #validates :content, :presence => true
  validates :allotment_id, :presence => true
end

app/models/claro_transaction_by_line_claro.rb
class ClaroTransactionByLineClaro < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
	

	validates :name, :presence => true
	validates :type_companies_id,  :presence => true
	belongs_to :type_companies, class_name: TypeCompany
	
end

app/models/consumer.rb
class Consumer < ActiveRecord::Base
	
end

app/models/pdf_file.rb
class PdfFile < ActiveRecord::Base
	
	attachment :pdf_file, extension: "pdf"
	
	validates :pdf_file, presence: true
	validates :allotments_id, presence: true
	validates :company_id, presence: true


	def lote_name
		return "#{Allotment.find_by_id(self.allotments_id).name}"
	end

end

app/models/type_company.rb
class TypeCompany < ActiveRecord::Base

	validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  #before_action :authenticate_user!

 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vivo_extract.rb
class VivoExtract < ActiveRecord::Base
  belongs_to :allotment
  belongs_to :pdf_file
end

app/models/vivo_group_word.rb
class VivoGroupWord < ActiveRecord::Base
end

app/models/vivo_header_manager.rb
class VivoHeaderManager < ActiveRecord::Base
  belongs_to :allotment
  belongs_to :pdf_file

  #enum type_enclosed: [:min, :gb, :regular, :mb]


end

app/controllers/claro_transaction_by_line_claros_controller.rb
class ClaroTransactionByLineClarosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_claro_transaction_by_line_claro, only: [:show, :edit, :update, :destroy]

  before_filter :authorize_admin, only: :index

  def authorize_admin
    redirect_to :back, :status => 401 unless current_user.admin
    #redirects to previous page
  end

  # GET /claro_transaction_by_line_claros
  # GET /claro_transaction_by_line_claros.json
  def index
    @claro_transaction_by_line_claros = ClaroTransactionByLineClaro.all
  end

  # GET /claro_transaction_by_line_claros/1
  # GET /claro_transaction_by_line_claros/1.json
  def show
  end

  # GET /claro_transaction_by_line_claros/new
  def new
    @claro_transaction_by_line_claro = ClaroTransactionByLineClaro.new
  end

  # GET /claro_transaction_by_line_claros/1/edit
  def edit
  end

  # POST /claro_transaction_by_line_claros
  # POST /claro_transaction_by_line_claros.json
  def create
    @claro_transaction_by_line_claro = ClaroTransactionByLineClaro.new(claro_transaction_by_line_claro_params)

    respond_to do |format|
      if @claro_transaction_by_line_claro.save
        format.html { redirect_to @claro_transaction_by_line_claro, notice: 'Claro transaction by line claro was successfully created.' }
        format.json { render :show, status: :created, location: @claro_transaction_by_line_claro }
      else
        format.html { render :new }
        format.json { render json: @claro_transaction_by_line_claro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /claro_transaction_by_line_claros/1
  # PATCH/PUT /claro_transaction_by_line_claros/1.json
  def update
    respond_to do |format|
      if @claro_transaction_by_line_claro.update(claro_transaction_by_line_claro_params)
        format.html { redirect_to @claro_transaction_by_line_claro, notice: 'Claro transaction by line claro was successfully updated.' }
        format.json { render :show, status: :ok, location: @claro_transaction_by_line_claro }
      else
        format.html { render :edit }
        format.json { render json: @claro_transaction_by_line_claro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /claro_transaction_by_line_claros/1
  # DELETE /claro_transaction_by_line_claros/1.json
  def destroy
    @claro_transaction_by_line_claro.destroy
    respond_to do |format|
      format.html { redirect_to claro_transaction_by_line_claros_url, notice: 'Claro transaction by line claro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_claro_transaction_by_line_claro
      @claro_transaction_by_line_claro = ClaroTransactionByLineClaro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def claro_transaction_by_line_claro_params
      params.require(:claro_transaction_by_line_claro).permit(:name, :kind, :value, :allotment_id, :id_file)
    end
end

app/helpers/allotments_helper.rb
module AllotmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claro_transaction_by_line_claros_helper.rb
module ClaroTransactionByLineClarosHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/consumers_helper.rb
module ConsumersHelper
end

app/helpers/data_pdfs_helper.rb
module DataPdfsHelper
end

app/helpers/lote_wizard_helper.rb
module LoteWizardHelper
end

app/helpers/new_lote_helper.rb
module NewLoteHelper
end

app/helpers/pdf_files_helper.rb
module PdfFilesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/process_pdf_helper.rb
module ProcessPdfHelper
end

app/views/claro_transaction_by_line_claros/_form.html.erb
<%= form_for(@claro_transaction_by_line_claro) do |f| %>
  <% if @claro_transaction_by_line_claro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@claro_transaction_by_line_claro.errors.count, "error") %> prohibited this claro_transaction_by_line_claro from being saved:</h2>

      <ul>
      <% @claro_transaction_by_line_claro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :allotment_id %><br>
    <%= f.number_field :allotment_id %>
  </div>
  <div class="field">
    <%= f.label :id_file %><br>
    <%= f.text_field :id_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/claro_transaction_by_line_claros/edit.html.erb
<h1>Editing Claro Transaction By Line Claro</h1>

<%= render 'form' %>

<%= link_to 'Show', @claro_transaction_by_line_claro %> |
<%= link_to 'Back', claro_transaction_by_line_claros_path %>

app/views/claro_transaction_by_line_claros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Claro Transaction By Line Claros</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Kind</th>
      <th>Value</th>
      <th>Allotment</th>
      <th>Id file</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @claro_transaction_by_line_claros.each do |claro_transaction_by_line_claro| %>
      <tr>
        <td><%= claro_transaction_by_line_claro.name %></td>
        <td><%= claro_transaction_by_line_claro.kind %></td>
        <td><%= claro_transaction_by_line_claro.value %></td>
        <td><%= claro_transaction_by_line_claro.allotment_id %></td>
        <td><%= claro_transaction_by_line_claro.id_file %></td>
        <td><%= link_to 'Show', claro_transaction_by_line_claro %></td>
        <td><%= link_to 'Edit', edit_claro_transaction_by_line_claro_path(claro_transaction_by_line_claro) %></td>
        <td><%= link_to 'Destroy', claro_transaction_by_line_claro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Claro transaction by line claro', new_claro_transaction_by_line_claro_path %>

app/views/claro_transaction_by_line_claros/new.html.erb
<h1>New Claro Transaction By Line Claro</h1>

<%= render 'form' %>

<%= link_to 'Back', claro_transaction_by_line_claros_path %>

app/views/claro_transaction_by_line_claros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @claro_transaction_by_line_claro.name %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @claro_transaction_by_line_claro.kind %>
</p>

<p>
  <strong>Value:</strong>
  <%= @claro_transaction_by_line_claro.value %>
</p>

<p>
  <strong>Allotment:</strong>
  <%= @claro_transaction_by_line_claro.allotment_id %>
</p>

<p>
  <strong>Id file:</strong>
  <%= @claro_transaction_by_line_claro.id_file %>
</p>

<%= link_to 'Edit', edit_claro_transaction_by_line_claro_path(@claro_transaction_by_line_claro) %> |
<%= link_to 'Back', claro_transaction_by_line_claros_path %>